apiVersion: v1
kind: Service
metadata:
  name: tel-switch
  labels:
    app: tel-switch
    monitor: prom
spec:
  selector:
    app: tel-switch
  ports:
  - name: http
    port: 80
    targetPort: http
