apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom
spec:
  serviceMonitorSelector:
    matchLabels:
      monitor: prom
  resources:
    requests:
      memory: 200Mi
  enableAdminAPI: false
