apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: services
  labels:
    monitor: prom
spec:
  selector:
    matchLabels:
      monitor: prom
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 5s
