apiVersion: v1
kind: Service
metadata:
  name: call-control
  labels:
    app: call-control
    monitor: prom
spec:
  selector:
    app: call-control
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 80
    targetPort: http
